import uuid
from sqlalchemy import Column, Integer, String, Text, DateTime, JSON, Float, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from datetime import datetime

# We reuse the Base from db_models to ensure they share the same metadata for migrations
from app.models.db_models import Base

class SeasonPlan(Base):
    """Stores the seasonal agricultural roadmap generated by the YieldPlanner agent."""
    __tablename__ = "season_plans"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, index=True, nullable=False) # external_id
    crop = Column(String, nullable=False)
    season_year = Column(Integer, nullable=False) # e.g., 2026
    predicted_yield = Column(Float) # Estimated tons/bigha
    confidence_score = Column(Float) # ML model confidence (0-1)

    # JSON structure: { "planting_date": "...", "fertilizer_schedule": [], "harvest_window": "..." }
    plan_details = Column(JSON, nullable=True)

    status = Column(String, default="active") # 'active', 'completed', 'archived'
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

class HarvestBatch(Base):
    """The immutable ledger for farm-to-table traceability."""
    __tablename__ = "harvest_batches"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, index=True, nullable=False)
    crop = Column(String, nullable=False)
    quantity = Column(Float, nullable=False)
    unit = Column(String, default="kg")

    # Traceability Chain
    prev_hash = Column(String, nullable=True) # Hash of the previous batch in the chain
    current_hash = Column(String, nullable=False, index=True) # Current batch signature

    # Meta information for the 'Story'
    inputs_used = Column(JSON, nullable=True) # List of seeds/fertilizers
    harvest_date = Column(DateTime(timezone=True), server_default=func.now())
    qr_code_url = Column(String, nullable=True)

    certification_status = Column(String, default="unverified") # 'verified', 'organic', 'unverified'
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class SustainabilityMetric(Base):
    """Tracks carbon sequestration and green farming progress."""
    __tablename__ = "sustainability_metrics"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, index=True, nullable=False)

    carbon_score = Column(Float, default=0.0) # 0-100 score
    co2_offset_kg = Column(Float, default=0.0) # Total kg of CO2 sequestered

    # JSON list of verified practices: ["no-till", "cover-cropping", "reduced-nitrogen"]
    verified_practices = Column(JSON, nullable=True)

    last_calculated = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
