from fastapi import APIRouter, Depends, Query, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from pydantic import BaseModel
import logging

from app.db import get_db
from app.models.db_models import CuratedTip, User
# from app.crews.krishi_crew import KrishiCrewOrchestrator  # Lazy import to avoid circular deps

logger = logging.getLogger("AlertsAPI")
router = APIRouter()

from app.core.dependencies import orchestrator

class DailyAlertResponse(BaseModel):
    user_id: str
    crop: str
    tip_bn: str
    audio_url: str | None
    pest_risk_alert: str

@router.get("/daily", response_model=DailyAlertResponse)
async def get_daily_alert(
    user_id: str = Query(..., description="The user external ID"),
    crop: str = Query(..., description="The crop the farmer is currently growing"),
    lat: float = Query(None, description="Latitude for local weather search"),
    lon: float = Query(None, description="Longitude for local weather search"),
    db: AsyncSession = Depends(get_db)
):
    """
    Combines a static curated tip from the database with a dynamic 
    weather-based pest risk alert generated by the Alert Advisor Agent.
    """
    try:
        # 1. Fetch static tip from DB based on crop (mocking growth stage 30 days)
        result = await db.execute(
            select(CuratedTip).where(CuratedTip.crop == crop.lower()).limit(1)
        )
        tip = result.scalar_one_or_none()
        
        if tip:
            tip_bn = tip.tip_text_bn
            audio_url = tip.audio_url
        else:
            tip_bn = f"আপনার {crop} ফসলের যত্ন নিন এবং নিয়মিত সেচ দিন।"
            audio_url = None

        # 2. Generate dynamic pest risk alert using the Alert Advisor Agent
        prompt = f"Check pest risk for {crop}."
        gps_data = None
        if lat and lon:
            gps_data = {"lat": lat, "lon": lon}
            
        initial_state = {
            "transcript": prompt,
            "gps": gps_data,
            "image_path": None
        }
        
        # This will trigger the 'alerts' intent
        result_state = await orchestrator.ainvoke(initial_state)
        pest_risk_alert = result_state.get("reply_text", "Failed to retrieve risk data.")

        return DailyAlertResponse(
            user_id=user_id,
            crop=crop,
            tip_bn=tip_bn,
            audio_url=audio_url,
            pest_risk_alert=pest_risk_alert
        )

    except Exception as e:
        logger.error(f"Error generating daily alert: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="An error occurred while generating the daily alert.")
